version: 2.1
orbs:
  ruby: circleci/ruby@1.0

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7
      - image: mileschou/xdebug:7.3
    resource_class: small
    steps:
      - checkout
      - run: gem install bundler:2.2.10
      - run: bundle install
      - run:
          name: Run Tests
          command: |
            set -e
            bundle exec rspec $(circleci tests glob "spec/**/**/*_spec.rb" | circleci tests split --split-by=timings) \
                              --format progress \
                              --out test_results/rspec.xml
            ./tmp/cc-test-reporter format-coverage --prefix /app -t simplecov -o tmp/test-results/codeclimate.$(echo $CIRCLE_NODE_INDEX).json public/coverage/.resultset.json
      - run:
          name: Download CC test reporter
          command: |
            mkdir -p ./tmp
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - run:
          name: Upload coverage results to Code Climate
          command: |
            ./tmp/cc-test-reporter sum-coverage tmp/test-results/codeclimate.*.json -p 5 -o tmp/test-results/codeclimate.total.json
            ./tmp/cc-test-reporter upload-coverage -i tmp/test-results/codeclimate.total.json
